---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "catalog-migrationservice-deployment"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "catalog-migrationservice"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "surveysystem-apphost"
        app.kubernetes.io/component: "catalog-migrationservice"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.catalog_migrationservice.catalog_migrationservice_image }}"
          name: "catalog-migrationservice"
          envFrom:
            - configMapRef:
                name: "catalog-migrationservice-config"
            - secretRef:
                name: "catalog-migrationservice-secrets"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "surveysystem-apphost"
      app.kubernetes.io/component: "catalog-migrationservice"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
