---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "catalog-api-config"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "catalog-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.catalog_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.catalog_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.catalog_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.catalog_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.catalog_api.HTTP_PORTS }}"
  CATALOG_POSTGRES_DB_HOST: "{{ .Values.config.catalog_api.CATALOG_POSTGRES_DB_HOST }}"
  CATALOG_POSTGRES_DB_PORT: "{{ .Values.config.catalog_api.CATALOG_POSTGRES_DB_PORT }}"
  CATALOG_POSTGRES_DB_USERNAME: "{{ .Values.config.catalog_api.CATALOG_POSTGRES_DB_USERNAME }}"
  CATALOG_POSTGRES_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.catalog_api.CATALOG_POSTGRES_DB_JDBCCONNECTIONSTRING }}"
  CATALOG_POSTGRES_DB_DATABASENAME: "{{ .Values.config.catalog_api.CATALOG_POSTGRES_DB_DATABASENAME }}"
