---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "catalog-api-deployment"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "catalog-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "surveysystem-apphost"
        app.kubernetes.io/component: "catalog-api"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.catalog_api.catalog_api_image }}"
          name: "catalog-api"
          envFrom:
            - configMapRef:
                name: "catalog-api-config"
            - secretRef:
                name: "catalog-api-secrets"
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:5000"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "surveysystem-apphost"
      app.kubernetes.io/component: "catalog-api"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
