---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "catalog-api-service"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "catalog-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "catalog-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.catalog_api.port_http }}
      targetPort: {{ .Values.parameters.catalog_api.target_port_http }}
