---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "catalog-postgres-server-config"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "catalog-postgres-server"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  POSTGRES_HOST_AUTH_METHOD: "{{ .Values.config.catalog_postgres_server.POSTGRES_HOST_AUTH_METHOD }}"
  POSTGRES_INITDB_ARGS: "{{ .Values.config.catalog_postgres_server.POSTGRES_INITDB_ARGS }}"
  POSTGRES_USER: "{{ .Values.config.catalog_postgres_server.POSTGRES_USER }}"
