---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "reporting-redis-db-service"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "reporting-redis-db"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "reporting-redis-db"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 6379
      targetPort: 6379
