---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rabbit-mq-config"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "rabbit-mq"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.config.rabbit_mq.RABBITMQ_DEFAULT_USER }}"
