---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "rabbit-mq-service"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "rabbit-mq"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "rabbit-mq"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
