---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "gateway-config"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.gateway.ASPNETCORE_ENVIRONMENT }}"
  CATALOG_API_HTTP: "{{ .Values.config.gateway.CATALOG_API_HTTP }}"
  REVERSEPROXY__ROUTES__route0__MATCH__PATH: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route0__MATCH__PATH }}"
  REVERSEPROXY__ROUTES__route0__CLUSTERID: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route0__CLUSTERID }}"
  REVERSEPROXY__ROUTES__route1__MATCH__METHODS__0: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__MATCH__METHODS__0 }}"
  REVERSEPROXY__ROUTES__route1__MATCH__METHODS__1: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__MATCH__METHODS__1 }}"
  REVERSEPROXY__ROUTES__route1__MATCH__METHODS__2: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__MATCH__METHODS__2 }}"
  REVERSEPROXY__ROUTES__route1__MATCH__METHODS__3: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__MATCH__METHODS__3 }}"
  REVERSEPROXY__ROUTES__route1__MATCH__PATH: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__MATCH__PATH }}"
  REVERSEPROXY__ROUTES__route1__CLUSTERID: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__CLUSTERID }}"
  REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__PathRemovePrefix: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__PathRemovePrefix }}"
  REVERSEPROXY__ROUTES__route2__MATCH__METHODS__0: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route2__MATCH__METHODS__0 }}"
  REVERSEPROXY__ROUTES__route2__MATCH__METHODS__1: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route2__MATCH__METHODS__1 }}"
  REVERSEPROXY__ROUTES__route2__MATCH__PATH: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route2__MATCH__PATH }}"
  REVERSEPROXY__ROUTES__route2__CLUSTERID: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route2__CLUSTERID }}"
  REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__PathRemovePrefix: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__PathRemovePrefix }}"
  REVERSEPROXY__ROUTES__route3__MATCH__METHODS__0: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route3__MATCH__METHODS__0 }}"
  REVERSEPROXY__ROUTES__route3__MATCH__PATH: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route3__MATCH__PATH }}"
  REVERSEPROXY__ROUTES__route3__CLUSTERID: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route3__CLUSTERID }}"
  REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__PathRemovePrefix: "{{ .Values.config.gateway.REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__PathRemovePrefix }}"
  REVERSEPROXY__CLUSTERS__cluster_catalog-api__DESTINATIONS__destination1__ADDRESS: "{{ .Values.config.gateway.REVERSEPROXY__CLUSTERS__cluster_catalog_api__DESTINATIONS__destination1__ADDRESS }}"
  REVERSEPROXY__CLUSTERS__cluster_response-api__DESTINATIONS__destination1__ADDRESS: "{{ .Values.config.gateway.REVERSEPROXY__CLUSTERS__cluster_response_api__DESTINATIONS__destination1__ADDRESS }}"
  REVERSEPROXY__CLUSTERS__cluster_reporting-api__DESTINATIONS__destination1__ADDRESS: "{{ .Values.config.gateway.REVERSEPROXY__CLUSTERS__cluster_reporting_api__DESTINATIONS__destination1__ADDRESS }}"