---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gateway-service"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 5000
      targetPort: 5000
