---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "response-mongo-server-service"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "response-mongo-server"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "response-mongo-server"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 27017
      targetPort: 27017
